.PHONY: clean All

All:
	@echo "----------Building project:[ DRV_TEST - BuildSet ]----------"
	@cd "DRV_TEST" && make -f  "DRV_TEST.mk"
clean:
	@echo "----------Cleaning project:[ DRV_TEST - BuildSet ]----------"
	@cd "DRV_TEST" && make -f  "DRV_TEST.mk" clean
