#ifndef __CSI_CONFIG_H__
#define __CSI_CONFIG_H__
#define CONFIG_CHIP_SL02 1
#define CONFIG_KERNEL_NONE 1
#define CONFIG_HAVE_VIC 1
#define CONFIG_SEPARATE_IRQ_SP 1
#define CONFIG_ARCH_INTERRUPTSTACK 1024
#define CONFIG_MM_KERNEL_HEAPSIZE 24576
#define EMOSC_FREQ 8000000
#endif
